# -*- coding: utf-8 -*-
dico_Textes = {
"English":["Shortcut",
    "Back to title screen",
    "Start Resolution Estimation",
    "Parameter",
    "Number of\n points (>=5)",
    "Time",
    "Start Analysis over time",
    "Time evolution of a single parameter precision",
    "Time evolution of all parameters precisions",
    "Expected flux and detector effects",
    "Neutrino oscillations",
    "Quit",
    "Reset",
    "Start Analysis for all parameters",
    "Save",
    "Inverted hierarchy",
    "Resolution for a single parameter at a given time",
    "",
    "",
    "Plot oscillations",
    "Ploting mode",
    "Explore each oscillation individually",
    "Compare hierarchies",
    "Initial flavor",
    "Final flavor",
    "All values in compare mode",
    '"all values" incompatible with mode "Compare hierarchies" ', 
    "Entering B mode",
    "Are you sure to enter B mode?\nYou can leave it by re-clicking on the button or CTRL+B",
    "yes",
    "no",
    "Correlated parameters study",
    "Start multiparametric analysis",
    "Number of runs\nto average on (>=5)",
    "Start distinction analysis",
    "Distinction between hierarchies",
    "Already existing graph?",
    "Compatibilty problem",
    "Parameter ",
    " incompatible with hierarchy ",
    "Ok",
    "At least one parameter is incompatible with hierarchy ",
    "Hierachy influence on double beta invariant mass",
    "Number of points too low",
    "Number of points ",
    " must be >= 5"
    ]
,

"Francais":["Raccourci",
    "Retour à l'écran titre",
    "Démarrer l'estimation de la résolution",
    "Paramètre",
    "Nombre de\n points (>=5)",
    "Temps",
    "Démarrer l'analyse en fonction du temps",
    "Évolution temporelle de la précision d'un paramètre",
    "Évolution temporelle de la précision de tous les paramètres",
    "Flux attendu et effets du détecteur",
    "Oscillations des neutrinos",
    "Quitter",
    "Réinitialiser",
    "Démarrer l'analyse pour tous les paramètres",
    "Sauvegarder",
    "Hiérarchie inverse",
    "Résolution pour un paramètre unique à un instant donné",
    "",
    "",
    "Tracer les oscillations",
    "Mode \nd'affichage",
    "Explorer chaque oscillation individuellement",
    "Comparer les hiérarchies",
    "Saveur initiale",
    "Saveur finale",
    "Toutes les valeurs en mode comparaison",
    '"Toutes les valeurs" incompatible avec le mode "Comparer les hiérarchies"',
    "Entrée en mode B",
    "Êtes-vous sûr de vouloir entrer en mode B ?\nVous pouvez en sortir en recliquant sur le bouton ou avec CTRL+B",
    "oui",
    "non",
    "Étude des paramètres corrélés",
    "Démarrer l'analyse multiparamétrique",
    "Nombre de simulations\nmoyennées (>=5)",
    "Démarrer l'analyse de distinction",
    "Distinction entre les hiérarchies",
    "Graphique déjà existant ?",
    "Problème de compatibilité",
    "Paramètre ",
    " incompatible avec la hiérarchie ",
    "Ok",
    "Au moins un paramètre est incompatible avec la hiérarchie ",
    "Influence de la hiérarchie sur la masse invariante du double bêta",
    "Nombre de points trop faible",
    "Nombre de points ",
    " doit être >= 5"
],

"Português":[
    "Atalho",
    "Voltar para a tela inicial",
    "Iniciar estimativa de resolução",
    "Parâmetro",
    "Número de\n pontos (>=5)",
    "Tempo",
    "Iniciar análise ao longo do tempo",
    "Evolução temporal da precisão de um único parâmetro",
    "Evolução temporal da precisão de todos os parâmetros",
    "Fluxo esperado e efeitos do detector",
    "Oscilações de neutrinos",
    "Sair",
    "Redefinir",
    "Iniciar análise para todos os parâmetros",
    "Salvar",
    "Hierarquia invertida",
    "Resolução para um único parâmetro em um determinado momento",
    "",
    "",
    "Plotar oscilações",
    "Modo de\n exibição",
    "Explorar cada oscilação individualmente",
    "Comparar hierarquias",
    "Sabor inicial",
    "Sabor final",
    "Todos os valores no modo comparação",
    '"Todos os valores" incompatível com o modo "Comparar hierarquias"',
    "Entrando no modo B",
    "Tem certeza de que deseja entrar no modo B?\nVocê pode sair clicando novamente no botão ou pressionando CTRL+B",
    "sim",
    "não",
    "Estudo de parâmetros correlacionados",
    "Iniciar análise multiparamétrica",
    "Número de execuções\npara média (>=5)",
    "Iniciar análise de distinção",
    "Distinção entre hierarquias",
    "Gráfico já existente?",
    "Problema de compatibilidade",
    "Parâmetro ",
    " incompatível com a hierarquia ",
    "Ok",
    "Pelo menos um parâmetro é incompatível com a hierarquia ",
    "Influência da hierarquia na massa invariante do duplo beta",
    "Número de pontos muito baixo",
    "Número de pontos ",
    " deve ser >= 5"
]


}
